name: Pull Request & Master CI

# Controls when the workflow will run
on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ master ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        run: ./gradlew check --full-stacktrace
