name: Pull Request & Master CI

# Controls when the workflow will run
on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: Run Unit Tests ${{ matrix.Java }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '8', '17' ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt-openj9'
          java-version: ${{ matrix.java }}
      - run: ./gradlew check --full-stacktrace
