name: master branch

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  push:
    paths-ignore:
      - '*.md'
    branches: [ master ]

jobs:
  test:
    name: PR Check
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: check --full-stacktrace
      - if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: PR Test Failure Report
          path: build/reports/tests/test
